kind = "captain"
slots = [0,1,2,3,4,5,6,7]

[[attribute_mul]]
param = "mini_jump_y"
subparam = ""
value = 0.701

[[attribute_mul]]
param = "dash_speed"
subparam = ""
value = 1.024

[[attribute_mul]]
param = "run_speed_max"
subparam = ""
value = 1.058

[[param_int]]
param = "landing_attack_air_frame_hi"
subparam = ""
value = 7

[[param_int]]
param = "landing_attack_air_frame_n"
subparam = ""
value = 6

[[attribute_mul]]
param = "air_accel_y"
subparam = ""
value = 1.167

[[attribute_mul]]
param = "air_speed_y_stable"
subparam = ""
value = 1.126

[[attribute_mul]]
param = "dive_speed_y"
subparam = ""
value = 1.307

[[attribute_mul]]
param = "jump_speed_x"
subparam = ""
value = 1.333

[[attribute_mul]]
param = "jump_speed_x_mul"
subparam = ""
value = 1.04

[[attribute_mul]]
param = "ground_brake"
subparam = ""
value = 0.924

[[attribute_mul]]
param = "air_speed_x_stable"
subparam = ""
value = 1.024